application :
  port : ":8000"
  secret : "172y87f1"
postgres : 
  host : "localhost"
  port : 5432
  user : "testuser"
  password : "testpass"
  db_name : "testdb"
  max_open_connections : 10
  max_idle_connections : 2
  connection_max_life_time : 10
mongodb : 
  uri : "mongodb://testuser:testpass@localhost:27017/?authMechanism=SCRAM-SHA-1"
  max_pool : 10
  min_pool : 5
  max_idle_connections : 2
  db_name : "testing"
smtp : 
  host : "localhost"
  password : "testpass"
  username : "testuser"
  port : 5432
  sender : "sender"
